export enum TypeNote {
  DEVOIR_SUR_TABLE = 'DEVOIR_SUR_TABLE',

  INTERROGATION = 'INTERROGATION',

  PROJET = 'PROJET',

  DEVOIR_DE_MAISON = 'DEVOIR_DE_MAISON',

  PARTICIPATION = 'PARTICIPATION',
}
